reglas = {
	('int', '+', 'int') : 'int',
	('int', '-', 'int') : 'int',
	('int', '*', 'int') : 'int',
	('int', '/', 'int') : 'float',
	('int', '=', 'int') : 'int',
	('int', '>', 'int') : 'bool',
	('int', '<', 'int') : 'bool',
	('int', '>=', 'int') : 'bool',
	('int', '<=', 'int') : 'bool',
	('int', '==', 'int') : 'bool',
	('int', '!=', 'int') : 'bool',

	('float', '+', 'float') : 'float',
	('float', '-', 'float') : 'float',
	('float', '*', 'float') : 'float',
	('float', '/', 'float') : 'float',
	('float', '=', 'float') : 'float',
	('float', '>', 'float') : 'bool',
	('float', '<', 'float') : 'bool',
	('float', '>=', 'float') : 'bool',
	('float', '<=', 'float') : 'bool',
	('float', '==', 'float') : 'bool',
	('float', '!=', 'float') : 'bool',

	('int', '+', 'float') : 'float',
	('int', '-', 'float') : 'float',
	('int', '*', 'float') : 'float',
	('int', '/', 'float') : 'float',
	('int', '>', 'float') : 'bool',
	('int', '<', 'float') : 'bool',
	('int', '>=', 'float') : 'bool',
	('int', '<=', 'float') : 'bool',

	('float', '+', 'int') : 'float',
	('float', '-', 'int') : 'float',
	('float', '*', 'int') : 'float',
	('float', '/', 'int') : 'float',
	('float', '>', 'int') : 'bool',
	('float', '<', 'int') : 'bool',
	('float', '>=', 'int') : 'bool',
	('float', '<=', 'int') : 'bool',

	('bool', '&&', 'bool') : 'bool',
	('bool', '||', 'bool') : 'bool',
	('bool', '<', 'bool') : 'bool',
	('bool', '>', 'bool') : 'bool',
	('bool', '<=', 'bool') : 'bool',
	('bool', '>=', 'bool') : 'bool',
	('bool', '==', 'bool') : 'bool',
	('bool', '!=', 'bool') : 'bool',

	('array', '+', 'array') : 'array',
	('array', '*', 'array') : 'array',
}